name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Create Android files
        run: flutter create --platforms=android --project-name saudi_stock_tracker .

      - name: Get packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --debug --dart-define=SAHMK_API_KEY=${{ secrets.SAHMK_API_KEY }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Saudi-Stock-Tracker-APK
          path: build/app/outputs/flutter-apk/app-debug.apk
